# NumPy Arrays

In [11]:
import numpy as np

# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

## Accessing elements

In [7]:
print countries[0]
print countries[3]

Afghanistan
Angola


## Slicing

In [8]:
print countries[0:3]
print countries[:3]
print countries[17:]
print countries[:]

['Afghanistan' 'Albania' 'Algeria']
['Afghanistan' 'Albania' 'Algeria']
['Bhutan' 'Bolivia' 'Bosnia and Herzegovina']
['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']


## Element Types

In [9]:
print countries.dtype
print employment.dtype
print np.array([0, 1, 2, 3]).dtype
print np.array([1.0, 1.5, 2.0, 2.5]).dtype
print np.array([True, False, True]).dtype
print np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype

|S22
float64
int64
float64
bool
|S2


## Looping

In [10]:
for country in countries:
    print 'Examining country {}'.format(country)
for i in range(len(countries)):
    country = countries[i]
    country_employment = employment[i]
    print 'Country {} has employment {}'.format(country,
            country_employment)

Examining country Afghanistan
Examining country Albania
Examining country Algeria
Examining country Angola
Examining country Argentina
Examining country Armenia
Examining country Australia
Examining country Austria
Examining country Azerbaijan
Examining country Bahamas
Examining country Bahrain
Examining country Bangladesh
Examining country Barbados
Examining country Belarus
Examining country Belgium
Examining country Belize
Examining country Benin
Examining country Bhutan
Examining country Bolivia
Examining country Bosnia and Herzegovina
Country Afghanistan has employment 55.70000076
Country Albania has employment 51.40000153
Country Algeria has employment 50.5
Country Angola has employment 75.69999695
Country Argentina has employment 58.40000153
Country Armenia has employment 40.09999847
Country Australia has employment 61.5
Country Austria has employment 57.09999847
Country Azerbaijan has employment 60.90000153
Country Bahamas has employment 66.59999847
Country Bahrain has employmen

## Numpy functions

In [12]:
print employment.mean()
print employment.std()
print employment.max()
print employment.sum()

58.6850000385
9.33826911369
75.69999695
1173.70000077


## Max Employment

In [15]:
def max_employment(countries, employment):
    i = employment.argmax()
    return (countries[i], employment[i])

max_employment(countries, employment)

('Angola', 75.699996949999999)

## Arithmetic operations between 2 NumPy arrays

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 1, 2])

print a + b
print a - b
print a * b
print a / b
print a ** b

[2 4 4 6]
[0 0 2 2]
[1 4 3 8]
[1 1 3 2]
[ 1  4  3 16]


## Arithmetic operations between a NumPy array and a single number

In [17]:
a = np.array([1, 2, 3, 4])
b = 2

print a + b
print a - b
print a * b
print a / b
print a ** b

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0 1 1 2]
[ 1  4  9 16]


## Logical operations with NumPy arrays

In [19]:
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])

print a & b
print a | b
print ~a
print a & True
print a & False
print a | True
print a | False

[ True False False False]
[ True  True  True False]
[False False  True  True]
[ True  True False False]
[False False False False]
[ True  True  True  True]
[ True  True False False]


## Comparison operations between 2 NumPy Arrays

In [20]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

print a > b
print a >= b
print a < b
print a <= b
print a == b
print a != b

[False False False  True  True]
[False False  True  True  True]
[ True  True False False False]
[ True  True  True False False]
[False False  True False False]
[ True  True False  True  True]


## Comparison operations between a NumPy array and a single number

In [21]:
a = np.array([1, 2, 3, 4])
b = 2

print a > b
print a >= b
print a < b
print a <= b
print a == b
print a != b

[False False  True  True]
[False  True  True  True]
[ True False False False]
[ True  True False False]
[False  True False False]
[ True False  True  True]


## Overall Completion Rate

In [22]:
# Female school completion rate in 2007 for those 20 countries
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

def overall_completion_rate(female_completion, male_completion):
    return (female_completion + male_completion) * 0.5
print overall_completion_rate(female_completion, male_completion)

[  96.416025  102.644275  101.41129    93.316285  103.455575   98.148215
  102.35113    91.77855    92.835475   89.655755   99.218715   98.484275
   94.172835  117.335125   98.275645   33.04039    41.905225   90.962965
   57.08404    93.06015 ]


# Standardizing Data

In [24]:
# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

def standardize_data(values):
    mean = values.mean()
    std = values.std()
    return (values - mean) / std

country_name = 'Albania'
employment_std = standardize_data(employment)
for i in range(len(employment)):
    if country_name == countries[i]:
        print employment_std[i]

-0.780122999221
